### ISSUE TITLE
Unknown Error (error 999)

### ISSUE THREAD

**Issue by andrewpriddis** [shivendabhi/nvidia-project#1]
I'm not sure how to get passed this error. I have a Jetson Nano and have just cloned the repo and ran tennis-ball_detection.py:

[gstreamer] gstBufferManager -- recieved first frame, codec=MJPEG format=i420 width=1280 height=720 size=1382407
[cuda]   allocated 4 ring buffers (1382407 bytes each, 5529628 bytes total)
[cuda]   allocated 4 ring buffers (8 bytes each, 32 bytes total)
[gstreamer] gstreamer changed state from READY to PAUSED ==> mysink
[gstreamer] gstreamer message async-done ==> pipeline0
[gstreamer] gstreamer changed state from PAUSED to PLAYING ==> mysink
[gstreamer] gstreamer changed state from PAUSED to PLAYING ==> pipeline0
[cuda]   allocated 4 ring buffers (2764800 bytes each, 11059200 bytes total)
[gstreamer] gstreamer message qos ==> v4l2src0
[gstreamer] gstreamer message qos ==> v4l2src0
[gstreamer] gstreamer message qos ==> v4l2src0
[gstreamer] gstreamer message qos ==> v4l2src0
[gstreamer] gstreamer message qos ==> v4l2src0
[OpenGL] glDisplay -- set the window size to 1280x720
[OpenGL] creating 1280x720 texture (GL_RGB8 format, 2764800 bytes)
[cuda]   cudaGraphicsGLRegisterBuffer(&interop, allocDMA(type), cudaGraphicsRegisterFlagsFromGL(flags))
[cuda]      unknown error (error 999) (hex 0x3E7)
[cuda]      /home/siddirp/jetson-inference/utils/display/glTexture.cpp:360
[gstreamer] gstreamer message qos ==> v4l2src0
[gstreamer] gstreamer message qos ==> v4l2src0
[gstreamer] gstreamer message qos ==> v4l2src0
[gstreamer] gstreamer message qos ==> v4l2src0
[gstreamer] gstreamer message qos ==> v4l2src0
[cuda]   cudaGetLastError()
[cuda]      unknown error (error 999) (hex 0x3E7)
[cuda]      /home/siddirp/jetson-inference/utils/cuda/cudaYUV-YV12.cu:119
[cuda]   cudaI420ToRGB(input, (uchar3*)output, width, height)
[cuda]      unknown error (error 999) (hex 0x3E7)
[cuda]      /home/siddirp/jetson-inference/utils/cuda/cudaColorspace.cpp:53
[cuda]   cudaConvertColor(latestYUV, mFormatYUV, nextRGB, format, mOptions->width, mOptions->height)
[cuda]      unknown error (error 999) (hex 0x3E7)
[cuda]      /home/siddirp/jetson-inference/utils/codec/gstBufferManager.cpp:445
[gstreamer] gstBufferManager -- unsupported image format (rgb8)
[gstreamer]                     supported formats are:
[gstreamer]                        * rgb8
[gstreamer]                        * rgba8
[gstreamer]                        * rgb32f
[gstreamer]                        * rgba32f
[gstreamer] gstCamera::Capture() -- an error occurred retrieving the next image buffer
Traceback (most recent call last):
  File "tennis-ball_detection.py", line 38, in <module>
    img = camera.Capture()
Exception: jetson.utils -- videoSource failed to capture image
[gstreamer] gstCamera -- stopping pipeline, transitioning to GST_STATE_NULL
[gstreamer] gstCamera -- pipeline stopped

**Comment by shivendabhi** [comment]
Hey there, I'm not currently working on this project, let me try to figure it out, will get back to you soon. If you do plan on using this for something, it's not that great at detecting the tennis balls, there are probably better models out there. I definitely think it may have overfitted to the environment it was in, but I'll have to look into it. Lmk if you have any questions

**Comment by shivendabhi** [comment]
Looks like it has something to do with your camera and the way it is setup

**Comment by andrewpriddis** [comment]
It turns out the output can stream to an X-display.
